# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: printer/protobuf_test.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprinter/protobuf_test.proto\x12\x07printer\"\x1c\n\x07Mensaje\x12\x11\n\tprintThis\x18\x01 \x01(\t2<\n\x07Printer\x12\x31\n\tPrintThis\x12\x10.printer.Mensaje\x1a\x10.printer.Mensaje\"\x00\x42\x14\n\x12\x62\x61sic.grpc.printerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'printer.protobuf_test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022basic.grpc.printer'
  _globals['_MENSAJE']._serialized_start=40
  _globals['_MENSAJE']._serialized_end=68
  _globals['_PRINTER']._serialized_start=70
  _globals['_PRINTER']._serialized_end=130
# @@protoc_insertion_point(module_scope)
